import tkinter as tk

window = tk.Tk()
window.geometry("750x500")

title = tk.Label(window, text="SCHEDULING")
monday = tk.Label(window, text="MONDAY : ")
tuesday = tk.Label(window, text="TUESDAY : ")
wednesday = tk.Label(window, text="WEDNESDAY : ")
thursday = tk.Label(window, text="THURSDAY : ")
friday = tk.Label(window, text="FRIDAY : ")
saturday = tk.Label(window, text="SATURDAY : ")
sunday = tk.Label(window, text="SUNDAY : ")
start = tk.Label(window, text="START TIME")
end = tk.Label(window, text="END TIME")
monstart = tk.Entry(window, width=8, bg="white", fg="black")
tuestart = tk.Entry(window, width=8, bg="white", fg="black")
wedstart = tk.Entry(window, width=8, bg="white", fg="black")
thustart = tk.Entry(window, width=8, bg="white", fg="black")
fristart = tk.Entry(window, width=8, bg="white", fg="black")
satstart = tk.Entry(window, width=8, bg="white", fg="black")
sunstart = tk.Entry(window, width=8, bg="white", fg="black")

endmon = tk.Entry(window, width=8, bg="white", fg="black")
endtue = tk.Entry(window, width=8, bg="white", fg="black")
endwed = tk.Entry(window, width=8, bg="white", fg="black")
endtue = tk.Entry(window, width=8, bg="white", fg="black")
endthu = tk.Entry(window, width=8, bg="white", fg="black")
endfri = tk.Entry(window, width=8, bg="white", fg="black")
endsat = tk.Entry(window, width=8, bg="white", fg="black")
endsun = tk.Entry(window, width=8, bg="white", fg="black")


def update_schedule():
    a=[]
    a.append(monstart.get())
    a.append(endmon.get())
    print('Schedule : ')
    for i in a:
        print(i)
    print()


update = tk.Button(window, width=8, text="UPDATE", bg="white", fg="black", command=update_schedule)

monstart.insert(0, "8")
tuestart.insert(0, "8")
wedstart.insert(0, "8")
thustart.insert(0, "8")
fristart.insert(0, "8")
satstart.insert(0, "8")
sunstart.insert(0, "8")
endmon.insert(0, "17")
endtue.insert(0, "17")
endwed.insert(0, "17")
endthu.insert(0, "17")
endfri.insert(0, "17")
endsat.insert(0, "17")
endsun.insert(0, "17")

title.place(x=325, y=20)
monday.place(x=191, y=100)
tuesday.place(x=189, y=130)
wednesday.place(x=168, y=160)
thursday.place(x=179, y=190)
friday.place(x=204, y=220)
saturday.place(x=179, y=250)
sunday.place(x=195, y=280)
start.place(x=270, y=75)
end.place(x=390, y=75)
monstart.place(x=268, y=98)
tuestart.place(x=268, y=128)
wedstart.place(x=268, y=158)
thustart.place(x=268, y=188)
fristart.place(x=268, y=218)
satstart.place(x=268, y=248)
sunstart.place(x=268, y=278)
endmon.place(x=388, y=98)
endtue.place(x=388, y=128)
endwed.place(x=388, y=158)
endthu.place(x=388, y=188)
endfri.place(x=388, y=218)
endsat.place(x=388, y=248)
endsun.place(x=388, y=278)
update.place(x=325, y=308)

window.mainloop()

